export const STORES = [
  { id: 1, name: "Sultan Salmiyah", parking_total: 5, parking_available: 2, traffic: "Medium", traffic_level: 2, distance: "1.2 km", crowd: "Moderate", travel_time: "8 min", address: "Salmiyah, Block 12, Kuwait" },
  { id: 2, name: "Sultan Shaab", parking_total: 6, parking_available: 5, traffic: "Low", traffic_level: 1, distance: "3.5 km", crowd: "Low", travel_time: "15 min", address: "Shaab, Block 5, Kuwait" },
  { id: 3, name: "Sultan Rumaithiya", parking_total: 4, parking_available: 0, traffic: "High", traffic_level: 3, distance: "5.1 km", crowd: "High", travel_time: "22 min", address: "Rumaithiya, Block 9, Kuwait" },
  { id: 4, name: "Sultan Hawalli", parking_total: 8, parking_available: 6, traffic: "Low", traffic_level: 1, distance: "6.8 km", crowd: "Low", travel_time: "28 min", address: "Hawalli, Block 3, Kuwait" },
  { id: 5, name: "Sultan Fahaheel", parking_total: 10, parking_available: 4, traffic: "Medium", traffic_level: 2, distance: "12.3 km", crowd: "Moderate", travel_time: "35 min", address: "Fahaheel, Block 7, Kuwait" },
];

export type InvItem = {
  id: number; name: string; aisle: number;
  store1_qty: number; store2_qty: number; store3_qty: number; store4_qty: number; store5_qty: number;
  price: number; category: string;
};

export const INVENTORY: InvItem[] = [
  { id: 1, name: "Apple", aisle: 1, store1_qty: 5, store2_qty: 1, store3_qty: 0, store4_qty: 8, store5_qty: 3, price: 0.85, category: "Produce" },
  { id: 2, name: "Orange", aisle: 1, store1_qty: 7, store2_qty: 0, store3_qty: 4, store4_qty: 6, store5_qty: 2, price: 0.65, category: "Produce" },
  { id: 3, name: "Broccoli", aisle: 1, store1_qty: 2, store2_qty: 3, store3_qty: 0, store4_qty: 5, store5_qty: 1, price: 0.9, category: "Produce" },
  { id: 4, name: "Tomato", aisle: 1, store1_qty: 10, store2_qty: 8, store3_qty: 3, store4_qty: 0, store5_qty: 7, price: 0.4, category: "Produce" },
  { id: 5, name: "Banana", aisle: 1, store1_qty: 0, store2_qty: 6, store3_qty: 2, store4_qty: 9, store5_qty: 4, price: 0.3, category: "Produce" },
  { id: 6, name: "Carrot", aisle: 1, store1_qty: 4, store2_qty: 5, store3_qty: 1, store4_qty: 3, store5_qty: 0, price: 0.5, category: "Produce" },
  { id: 7, name: "Strawberry", aisle: 1, store1_qty: 3, store2_qty: 0, store3_qty: 5, store4_qty: 2, store5_qty: 6, price: 1.2, category: "Produce" },
  { id: 8, name: "Watermelon", aisle: 1, store1_qty: 2, store2_qty: 4, store3_qty: 0, store4_qty: 1, store5_qty: 3, price: 2.5, category: "Produce" },
  { id: 9, name: "Spinach", aisle: 1, store1_qty: 6, store2_qty: 2, store3_qty: 4, store4_qty: 0, store5_qty: 5, price: 0.75, category: "Produce" },
  { id: 10, name: "Cucumber", aisle: 1, store1_qty: 8, store2_qty: 7, store3_qty: 2, store4_qty: 4, store5_qty: 0, price: 0.35, category: "Produce" },
  { id: 11, name: "Whole Milk", aisle: 4, store1_qty: 4, store2_qty: 2, store3_qty: 6, store4_qty: 3, store5_qty: 5, price: 0.95, category: "Dairy" },
  { id: 12, name: "Yoghurt", aisle: 4, store1_qty: 6, store2_qty: 4, store3_qty: 0, store4_qty: 7, store5_qty: 2, price: 0.6, category: "Dairy" },
  { id: 13, name: "Cheddar Cheese", aisle: 4, store1_qty: 3, store2_qty: 5, store3_qty: 2, store4_qty: 0, store5_qty: 4, price: 2.1, category: "Dairy" },
  { id: 14, name: "Butter", aisle: 4, store1_qty: 5, store2_qty: 0, store3_qty: 3, store4_qty: 6, store5_qty: 1, price: 1.4, category: "Dairy" },
  { id: 15, name: "Cream Cheese", aisle: 4, store1_qty: 2, store2_qty: 3, store3_qty: 1, store4_qty: 4, store5_qty: 0, price: 1.8, category: "Dairy" },
  { id: 16, name: "Sour Cream", aisle: 4, store1_qty: 4, store2_qty: 1, store3_qty: 5, store4_qty: 2, store5_qty: 3, price: 1.1, category: "Dairy" },
  { id: 17, name: "Skimmed Milk", aisle: 4, store1_qty: 0, store2_qty: 6, store3_qty: 3, store4_qty: 5, store5_qty: 2, price: 0.85, category: "Dairy" },
  { id: 18, name: "Greek Yoghurt", aisle: 4, store1_qty: 7, store2_qty: 4, store3_qty: 0, store4_qty: 3, store5_qty: 6, price: 1.3, category: "Dairy" },
  { id: 19, name: "Chicken Breast", aisle: 3, store1_qty: 0, store2_qty: 3, store3_qty: 5, store4_qty: 2, store5_qty: 4, price: 3.5, category: "Meat & Deli" },
  { id: 20, name: "Beef Mince", aisle: 3, store1_qty: 4, store2_qty: 0, store3_qty: 2, store4_qty: 6, store5_qty: 1, price: 4.2, category: "Meat & Deli" },
  { id: 21, name: "Salmon Fillet", aisle: 3, store1_qty: 2, store2_qty: 5, store3_qty: 0, store4_qty: 3, store5_qty: 4, price: 6.5, category: "Meat & Deli" },
  { id: 22, name: "Lamb Chops", aisle: 3, store1_qty: 3, store2_qty: 1, store3_qty: 4, store4_qty: 0, store5_qty: 2, price: 7.8, category: "Meat & Deli" },
  { id: 23, name: "Turkey Slices", aisle: 3, store1_qty: 5, store2_qty: 4, store3_qty: 1, store4_qty: 2, store5_qty: 0, price: 2.9, category: "Meat & Deli" },
  { id: 24, name: "Tuna Can", aisle: 3, store1_qty: 8, store2_qty: 6, store3_qty: 4, store4_qty: 5, store5_qty: 3, price: 1.2, category: "Meat & Deli" },
  { id: 25, name: "Frozen Peas", aisle: 2, store1_qty: 6, store2_qty: 3, store3_qty: 5, store4_qty: 0, store5_qty: 4, price: 1.1, category: "Frozen Food" },
  { id: 26, name: "Frozen Pizza", aisle: 2, store1_qty: 3, store2_qty: 5, store3_qty: 0, store4_qty: 4, store5_qty: 2, price: 3.8, category: "Frozen Food" },
  { id: 27, name: "Ice Cream", aisle: 2, store1_qty: 4, store2_qty: 0, store3_qty: 6, store4_qty: 3, store5_qty: 5, price: 2.2, category: "Frozen Food" },
  { id: 28, name: "Frozen Chips", aisle: 2, store1_qty: 7, store2_qty: 4, store3_qty: 2, store4_qty: 5, store5_qty: 0, price: 1.5, category: "Frozen Food" },
  { id: 29, name: "Frozen Shrimp", aisle: 2, store1_qty: 2, store2_qty: 6, store3_qty: 0, store4_qty: 1, store5_qty: 3, price: 5.5, category: "Frozen Food" },
  { id: 30, name: "Noodles", aisle: 2, store1_qty: 5, store2_qty: 0, store3_qty: 3, store4_qty: 6, store5_qty: 2, price: 1.8, category: "Frozen Food" },
  { id: 31, name: "Chocolate", aisle: 5, store1_qty: 3, store2_qty: 6, store3_qty: 4, store4_qty: 5, store5_qty: 2, price: 0.85, category: "Snacks" },
  { id: 32, name: "Potato Chips", aisle: 5, store1_qty: 8, store2_qty: 5, store3_qty: 3, store4_qty: 7, store5_qty: 4, price: 0.75, category: "Snacks" },
  { id: 33, name: "Granola Bar", aisle: 5, store1_qty: 5, store2_qty: 3, store3_qty: 0, store4_qty: 4, store5_qty: 6, price: 1.1, category: "Snacks" },
  { id: 34, name: "Popcorn", aisle: 5, store1_qty: 4, store2_qty: 7, store3_qty: 2, store4_qty: 0, store5_qty: 3, price: 0.95, category: "Snacks" },
  { id: 35, name: "Mixed Nuts", aisle: 5, store1_qty: 2, store2_qty: 4, store3_qty: 5, store4_qty: 3, store5_qty: 0, price: 2.8, category: "Snacks" },
  { id: 36, name: "Rice Crackers", aisle: 5, store1_qty: 6, store2_qty: 0, store3_qty: 4, store4_qty: 2, store5_qty: 5, price: 1.3, category: "Snacks" },
  { id: 37, name: "White Rice", aisle: 6, store1_qty: 9, store2_qty: 7, store3_qty: 5, store4_qty: 8, store5_qty: 6, price: 2.5, category: "Grains" },
  { id: 38, name: "Brown Rice", aisle: 6, store1_qty: 5, store2_qty: 3, store3_qty: 4, store4_qty: 6, store5_qty: 0, price: 3.2, category: "Grains" },
  { id: 39, name: "Whole Wheat Bread", aisle: 6, store1_qty: 4, store2_qty: 6, store3_qty: 0, store4_qty: 3, store5_qty: 5, price: 1.2, category: "Grains" },
  { id: 40, name: "Pasta", aisle: 6, store1_qty: 7, store2_qty: 5, store3_qty: 3, store4_qty: 0, store5_qty: 4, price: 0.9, category: "Grains" },
  { id: 41, name: "Oats", aisle: 6, store1_qty: 3, store2_qty: 4, store3_qty: 6, store4_qty: 5, store5_qty: 0, price: 1.8, category: "Grains" },
  { id: 42, name: "Quinoa", aisle: 6, store1_qty: 2, store2_qty: 0, store3_qty: 3, store4_qty: 4, store5_qty: 5, price: 4.5, category: "Grains" },
  { id: 43, name: "Orange Juice", aisle: 7, store1_qty: 6, store2_qty: 4, store3_qty: 2, store4_qty: 5, store5_qty: 3, price: 1.5, category: "Beverages" },
  { id: 44, name: "Mineral Water", aisle: 7, store1_qty: 12, store2_qty: 10, store3_qty: 8, store4_qty: 9, store5_qty: 11, price: 0.25, category: "Beverages" },
  { id: 45, name: "Green Tea", aisle: 7, store1_qty: 4, store2_qty: 5, store3_qty: 3, store4_qty: 0, store5_qty: 6, price: 2.1, category: "Beverages" },
  { id: 46, name: "Coffee Beans", aisle: 7, store1_qty: 3, store2_qty: 2, store3_qty: 5, store4_qty: 4, store5_qty: 0, price: 5.8, category: "Beverages" },
  { id: 47, name: "Coconut Water", aisle: 7, store1_qty: 5, store2_qty: 0, store3_qty: 4, store4_qty: 3, store5_qty: 6, price: 1.9, category: "Beverages" },
  { id: 48, name: "Dish Soap", aisle: 8, store1_qty: 8, store2_qty: 6, store3_qty: 4, store4_qty: 7, store5_qty: 5, price: 1.1, category: "Household" },
  { id: 49, name: "Laundry Detergent", aisle: 8, store1_qty: 5, store2_qty: 3, store3_qty: 0, store4_qty: 6, store5_qty: 4, price: 3.5, category: "Household" },
  { id: 50, name: "Tissue Box", aisle: 8, store1_qty: 10, store2_qty: 8, store3_qty: 6, store4_qty: 9, store5_qty: 7, price: 0.95, category: "Household" },
];

export const CHECKOUT_LANES = [
  { id: 1, lane: "Lane 1", queue: 5, items_avg: 18, wait_time: "7 min", status: "red" },
  { id: 2, lane: "Lane 2", queue: 3, items_avg: 12, wait_time: "5 min", status: "yellow" },
  { id: 3, lane: "Lane 3", queue: 2, items_avg: 8, wait_time: "3 min", status: "yellow" },
  { id: 4, lane: "Lane 4 (Self)", queue: 1, items_avg: 5, wait_time: "1 min", status: "green" },
  { id: 5, lane: "Lane 5", queue: 1, items_avg: 6, wait_time: "2 min", status: "green" },
  { id: 6, lane: "Lane 6", queue: 6, items_avg: 20, wait_time: "9 min", status: "red" },
  { id: 7, lane: "Lane 7 (Express)", queue: 2, items_avg: 7, wait_time: "2 min", status: "green" },
];

export const FOOD_PRODUCT = {
  name: "Organic Whole Milk",
  producer: "FreshFarm Co.",
  prod_date: "2025-04-20",
  exp_date: "2025-05-20",
  max_storage_temp: -0.1,
  opt_storage_temp: 1.5,
  freshness: "Fresh",
  distribution: [
    { plant: "Processing Plant A", arrive: "2025-04-20 08:00", depart: "2025-04-20 14:00" },
    { plant: "Warehouse B", arrive: "2025-04-21 06:00", depart: "2025-04-22 09:00" },
    { plant: "Sultan Salmiyah Store", arrive: "2025-04-23 07:00", depart: null as string | null },
  ],
  temp_log: [
    { time: "Apr 20", temp: 1.2 }, { time: "Apr 21", temp: 1.5 },
    { time: "Apr 22", temp: 2.1 }, { time: "Apr 23", temp: 1.8 },
    { time: "Apr 24", temp: 1.3 }, { time: "Apr 25", temp: 1.6 },
    { time: "Apr 26", temp: 3.8 }, { time: "Apr 27", temp: 1.9 },
    { time: "Apr 28", temp: 1.4 }, { time: "Apr 29", temp: 1.7 },
  ],
};

export const STORE_MAP = {
  sections: [
    { id: 1, name: "Produce", x: 5, y: 5, w: 30, h: 20, color: "#4CAF50" },
    { id: 2, name: "Frozen Food", x: 40, y: 5, w: 30, h: 20, color: "#2196F3" },
    { id: 3, name: "Meat & Deli", x: 75, y: 5, w: 20, h: 20, color: "#F44336" },
    { id: 4, name: "Dairy", x: 5, y: 35, w: 20, h: 20, color: "#9C27B0" },
    { id: 5, name: "Snacks", x: 30, y: 35, w: 25, h: 20, color: "#FF9800" },
    { id: 6, name: "Grains", x: 60, y: 35, w: 35, h: 20, color: "#795548" },
    { id: 7, name: "Beverages", x: 5, y: 62, w: 35, h: 18, color: "#00BCD4" },
    { id: 8, name: "Household", x: 45, y: 62, w: 50, h: 18, color: "#607D8B" },
    { id: 9, name: "Checkout", x: 20, y: 85, w: 60, h: 12, color: "#455A64" },
  ],
  user_position: { x: 12, y: 72, label: "You are here" },
};

export const CATEGORIES = ["All", "Produce", "Dairy", "Meat & Deli", "Frozen Food", "Snacks", "Grains", "Beverages", "Household"];

export const CATEGORY_ICONS: Record<string, string> = {
  Produce: "🥦", Dairy: "🥛", "Meat & Deli": "🥩", "Frozen Food": "🧊",
  Snacks: "🍫", Grains: "🌾", Beverages: "🧃", Household: "🧴",
};

/* ================= TRANSLATIONS ================= */
export type Lang = "en" | "my";

export const translations = {
  en: {
    appName: "sysMART", tagline: "Your Smart Supermarket Assistant",
    back: "Back", confirm: "Confirm", cancel: "Cancel", submit: "Submit",
    search: "Search", loading: "Loading...", done: "Done", close: "Close",
    yes: "Yes", no: "No",
    welcome: "Welcome to sysMART", linkCart: "Link your cart to get started",
    selectStore: "Select Your Store", enterCart: "Enter cart number e.g. Cart-01",
    startShopping: "Start Shopping", browseWithout: "Browse without cart",
    cartError: "Please enter your cart number", cartLinked: "Cart linked successfully",
    greeting: "Good morning, Shopper", searchPlaceholder: "Search products, services...",
    indoorNav: "Indoor Navigation", indoorNavDesc: "Find products & navigate aisles",
    fastestCheckout: "Fastest Checkout", fastestCheckoutDesc: "Find the shortest queue",
    iNeedHelp: "I Need Help", iNeedHelpDesc: "Request staff assistance",
    reportIssue: "Report Issue", reportIssueDesc: "Report cart malfunction",
    foodTracker: "Food Tracker", foodTrackerDesc: "Check freshness & storage",
    outdoorServices: "Outdoor Services", outdoorServicesDesc: "Parking, traffic & inventory",
    services: "Services",
    howManyItems: "How many items are you buying?", findBestLane: "Find Best Lane",
    recommendedLane: "Recommended for you", navigateToLane: "Navigate to Lane",
    laneSelected: "Lane Selected!",
    whatHelp: "What kind of help do you need?",
    staffAssistance: "Staff Assistance", medicalEmergency: "Medical Emergency",
    productAssistance: "Product Assistance", accessibilitySupport: "Accessibility Support",
    helpOnWay: "Help is on the way!", estimatedResponse: "Estimated response: 2-3 minutes",
    emergency: "EMERGENCY — Tap for immediate help",
    reportCartIssue: "Report Cart Issue",
    brokenWheel: "Broken Wheel", scannerIssue: "Scanner Issue",
    batteryIssue: "Battery Issue", navigationIssue: "Navigation Issue",
    otherIssue: "Other Issue", reportSubmitted: "Report Submitted Successfully",
    nfcInstruction: "Hold your phone close to the product NFC tag",
    simulateScan: "Simulate NFC Scan", manualEntry: "Enter product code",
    productDetails: "Product Details", producer: "Producer",
    productionDate: "Production Date", expiryDate: "Expiry Date",
    freshness: "Freshness", fresh: "FRESH", monitor: "MONITOR", warning: "WARNING",
    viewTempHistory: "View Temperature History",
    storageConditionsSafe: "Storage conditions remained safe",
    indoorNavigation: "Indoor Navigation",
    browseCategory: "Browse by Category", searchByName: "Search by Name",
    navigateToProduct: "Navigate to Product", youAreHere: "You are here",
    arrived: "You've arrived!", findAnother: "Find Another Product",
    goToCheckout: "Go to Checkout", resetNavigation: "Reset Navigation",
    clearNavigation: "Clear navigation and start over?",
    planYourVisit: "Plan your visit", trafficParking: "Traffic & Parking",
    storeInventory: "Store Inventory Search", nearbyStores: "Nearby Stores",
    parkingAvailable: "parking spots free", setAsMyStore: "Set as My Store",
    myProfile: "My Profile", settings: "Settings", darkMode: "Dark Mode",
    notifications: "Notifications", accessibilityMode: "Accessibility Mode",
    language: "Language", locateAFriend: "Locate a Friend",
    logout: "Logout", logoutConfirm: "Are you sure you want to logout?",
    allowLocation: "Allow Location Access",
    locationDesc: "sysMART uses your location to show nearby stores, parking, and traffic closest to you.",
    allowBtn: "Allow Location", notNow: "Not Now",
    locationActive: "Location Active",
    locationOff: "Location access off — distances are estimated",
    locationServices: "Location Services",
    nearestToYou: "Nearest to you", basedOnLocation: "Based on your current location",
    home: "Home", scan: "Scan", navigate: "Navigate",
    cartRequired: "Cart Required",
    cartRequiredDesc: "This feature requires a linked cart. Link your cart to access Indoor Navigation, Checkout, and Assistance features.",
    linkMyCart: "Link My Cart", continueGuest: "Continue as Guest",
    guestMode: "Guest Mode", login: "Login",
    linkCartUnlock: "Link a cart to unlock all features",
    fontSize: "Font Size", standard: "Standard", large: "Large", xlarge: "Extra Large",
    highContrast: "High Contrast Text", extraSpacing: "Extra Spacing",
    selectItems: "Select items to search", searchSelected: "Search",
    itemsSelected: "items selected",
    items: "items", outOfStock: "Out of stock at this store",
    findAtOther: "Find at another store",
    arHelp: "AR simulation mode — real AR uses device camera",
    headTo: "Head to", ahead: "ahead", switchToAR: "Switch to AR View",
    iAmHere: "I'm Here", arNavigation: "AR Navigation",
    foundIn: "Found in Aisle", indoorWifi: "Using store Wi-Fi positioning for indoor navigation",
    loggedOut: "Logged out successfully",
  },
  my: {
    appName: "sysMART", tagline: "Pembantu Pasar Raya Pintar Anda",
    back: "Kembali", confirm: "Sahkan", cancel: "Batal", submit: "Hantar",
    search: "Cari", loading: "Memuatkan...", done: "Selesai", close: "Tutup",
    yes: "Ya", no: "Tidak",
    welcome: "Selamat Datang ke sysMART", linkCart: "Hubungkan troli anda untuk bermula",
    selectStore: "Pilih Kedai Anda", enterCart: "Masukkan nombor troli cth. Cart-01",
    startShopping: "Mula Membeli-belah", browseWithout: "Semak imbas tanpa troli",
    cartError: "Sila masukkan nombor troli anda", cartLinked: "Troli berjaya dihubungkan",
    greeting: "Selamat pagi, Pelanggan", searchPlaceholder: "Cari produk, perkhidmatan...",
    indoorNav: "Navigasi Dalaman", indoorNavDesc: "Cari produk & navigasi lorong",
    fastestCheckout: "Pembayaran Terpantas", fastestCheckoutDesc: "Cari barisan terpendek",
    iNeedHelp: "Saya Perlukan Bantuan", iNeedHelpDesc: "Minta bantuan kakitangan",
    reportIssue: "Laporkan Masalah", reportIssueDesc: "Laporkan kerosakan troli",
    foodTracker: "Penjejak Makanan", foodTrackerDesc: "Semak kesegaran & penyimpanan",
    outdoorServices: "Perkhidmatan Luar", outdoorServicesDesc: "Tempat letak kereta, trafik & inventori",
    services: "Perkhidmatan",
    howManyItems: "Berapa banyak item yang anda beli?", findBestLane: "Cari Lorong Terbaik",
    recommendedLane: "Disyorkan untuk anda", navigateToLane: "Navigasi ke Lorong",
    laneSelected: "Lorong Dipilih!",
    whatHelp: "Apakah jenis bantuan yang anda perlukan?",
    staffAssistance: "Bantuan Kakitangan", medicalEmergency: "Kecemasan Perubatan",
    productAssistance: "Bantuan Produk", accessibilitySupport: "Sokongan Aksesibiliti",
    helpOnWay: "Bantuan sedang dalam perjalanan!", estimatedResponse: "Anggaran respons: 2-3 minit",
    emergency: "KECEMASAN — Ketik untuk bantuan segera",
    reportCartIssue: "Laporkan Masalah Troli",
    brokenWheel: "Roda Rosak", scannerIssue: "Masalah Pengimbas",
    batteryIssue: "Masalah Bateri", navigationIssue: "Masalah Navigasi",
    otherIssue: "Masalah Lain", reportSubmitted: "Laporan Berjaya Dihantar",
    nfcInstruction: "Pegang telefon anda dekat dengan tag NFC produk",
    simulateScan: "Simulasi Imbasan NFC", manualEntry: "Masukkan kod produk",
    productDetails: "Butiran Produk", producer: "Pengeluar",
    productionDate: "Tarikh Pengeluaran", expiryDate: "Tarikh Luput",
    freshness: "Kesegaran", fresh: "SEGAR", monitor: "PANTAU", warning: "AMARAN",
    viewTempHistory: "Lihat Sejarah Suhu",
    storageConditionsSafe: "Keadaan penyimpanan kekal selamat",
    indoorNavigation: "Navigasi Dalaman",
    browseCategory: "Semak Mengikut Kategori", searchByName: "Cari Mengikut Nama",
    navigateToProduct: "Navigasi ke Produk", youAreHere: "Anda di sini",
    arrived: "Anda telah tiba!", findAnother: "Cari Produk Lain",
    goToCheckout: "Pergi ke Pembayaran", resetNavigation: "Set Semula Navigasi",
    clearNavigation: "Kosongkan navigasi dan mulakan semula?",
    planYourVisit: "Rancang lawatan anda", trafficParking: "Trafik & Tempat Letak Kereta",
    storeInventory: "Carian Inventori Kedai", nearbyStores: "Kedai Berhampiran",
    parkingAvailable: "tempat letak kereta kosong", setAsMyStore: "Tetapkan sebagai Kedai Saya",
    myProfile: "Profil Saya", settings: "Tetapan", darkMode: "Mod Gelap",
    notifications: "Pemberitahuan", accessibilityMode: "Mod Aksesibiliti",
    language: "Bahasa", locateAFriend: "Cari Rakan",
    logout: "Log Keluar", logoutConfirm: "Adakah anda pasti mahu log keluar?",
    allowLocation: "Benarkan Akses Lokasi",
    locationDesc: "sysMART menggunakan lokasi anda untuk menunjukkan kedai berhampiran, tempat letak kereta dan trafik.",
    allowBtn: "Benarkan Lokasi", notNow: "Tidak Sekarang",
    locationActive: "Lokasi Aktif",
    locationOff: "Akses lokasi dimatikan — jarak adalah anggaran",
    locationServices: "Perkhidmatan Lokasi",
    nearestToYou: "Terdekat dengan anda", basedOnLocation: "Berdasarkan lokasi anda",
    home: "Utama", scan: "Imbas", navigate: "Navigasi",
    cartRequired: "Troli Diperlukan",
    cartRequiredDesc: "Ciri ini memerlukan troli yang dihubungkan. Hubungkan troli untuk menggunakan Navigasi Dalaman, Pembayaran dan Bantuan.",
    linkMyCart: "Hubungkan Troli Saya", continueGuest: "Teruskan Sebagai Tetamu",
    guestMode: "Mod Tetamu", login: "Log Masuk",
    linkCartUnlock: "Hubungkan troli untuk membuka semua ciri",
    fontSize: "Saiz Fon", standard: "Standard", large: "Besar", xlarge: "Sangat Besar",
    highContrast: "Teks Kontras Tinggi", extraSpacing: "Jarak Tambahan",
    selectItems: "Pilih item untuk dicari", searchSelected: "Cari",
    itemsSelected: "item dipilih",
    items: "item", outOfStock: "Kehabisan stok di kedai ini",
    findAtOther: "Cari di kedai lain",
    arHelp: "Mod simulasi AR — AR sebenar menggunakan kamera peranti",
    headTo: "Pergi ke", ahead: "di hadapan", switchToAR: "Tukar ke Paparan AR",
    iAmHere: "Saya di Sini", arNavigation: "Navigasi AR",
    foundIn: "Dijumpai di Lorong", indoorWifi: "Menggunakan kedudukan Wi-Fi kedai untuk navigasi dalaman",
    loggedOut: "Berjaya log keluar",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
